name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Log in to Amazon ECR
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 194722438687.dkr.ecr.ap-south-1.amazonaws.com/githubactiones

      - name: Build, tag, and push Docker image to ECR
        run: |
          IMAGE_URI=194722438687.dkr.ecr.ap-south-1.amazonaws.com/githubactiones:latest
          docker build -t my-app .
          docker tag my-app:latest $IMAGE_URI
          docker push $IMAGE_URI

      - name: Update ECS service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecs update-service --cluster github --service github --force-new-deployment

